"""Adiciona campo custo no produto

Revision ID: fe1788d9d252
Revises: ca0c132aaad6
Create Date: 2026-01-07 10:42:06.963070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1788d9d252'
down_revision = 'ca0c132aaad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
